amsul/pickadate.js

README.md
Changed branch for contributing link to master because gh-pages leads to a 404 page
=> #864 Fixed link to Contributing Page

lib/picker.date.js, lib/picker.time.js
load with `require('pickadate/lib/picker.date')` and/or
`require('pickadate/lib/picker.time')` with jQuery in a global
namespace.
Works with https://github.com/amsul/pickadate.js/pull/772, but #772 is
not necessary.
=> webpack compatibility

lib/translations/et_EE.js
The estonian translation for 'clear' was wrong. It was 'kustutama', which is the base form, but in this context it needs to be 'kustuta'. This pull would fix that.
=> Fixed estonian translation 'clear'

lib/translations/hu_HU.js
We do not capitalize the second letter of digraphs in Hungarian
=> Fix capitalization error in Hungarian translation

lib/translations/ca_ES.js
Infinitive for verbs that "talk" to the system are not used in Catalan. Imperative is used instead.
[MS Style Guides](http://download.microsoft.com/download/F/0/6/F06507FB-0BEE-4856-86B3-CB7500C5DC01/cat-esp-StyleGuide.pdf) reflect this:
> Use the 2nd person singular of the imperative (tu) to address the system. Unlike English and Spanish, the infinitive form should never be used in Catalan.
=> Correct Catalan verbs according to the Style Guide

lib/translations/zh_TW.js
Fixed the translation "close" to traditional chinese, the original translation may be copy from "zh_CN.js" that is different between Traditional Chinese(TW) and Simplified Chinese(CN).
=> Fixed the translation "close" to traditional chinese

lib/picker.js, lib/themes-source/default.less, lib/themes/default.css
New setting `inline`, which adds a `picker--inline` class to the root div. This styles the picker so that it is statically positioned instead of fixed/absolute, as well as cosmetic changes. The setting also disables the close() function, instead triggering an `onInlineClose` event for which a callback can be passed upon picker creation.
=> Added inline option

lib/translations/zh_CN.js
Because I find the 9th line and the last two lines is the same effect.The last two lines is repeated and chrome throw error that last two lines produce.
I am Chinese and like this plug that use our site very much.I hope to contribute for pickadate.js.Thank you very much.
-delete last two lines in zh_CN.js file.
=> zh_CN.js file,the last two lines maybe not be required.

lib/translations/hr_HR.js
Proof:
https://translate.google.com/#auto/hr/january
=> January misspelled

lib/translations/zh_CN.js
We usually use "今天" instead of "今日" in Simplified Chinese (although there are no differences between them).
=> update Chinese translation

lib/picker.js
Closes #1032
Thanks go to @Mwni for finding a solution
=> Prevent Chrome 62 autofill from closing the picker

lib/picker.date.js
Using UTC values prevents a browser specific issue where the day immediately following the end or start of DST in certain regions will be displayed as the day before. E.g. The 14th of October will be displayed twice in Firefox in computers whose locale is set to BR.
=> Using UTC values prevents a browser specific issue with DST in certain regions

lib/themes/classic.css
Currently the element "picker__holder" was repainted every scroll, even though it was invisible. I'm not sure why, but this property fixes it (invisible elements should be out of "calculation").
=> Prevent paint when hidden

lib/picker.js
relates to:
https://github.com/amsul/pickadate.js/issues/40
https://github.com/amsul/pickadate.js/issues/265
First of all, thanks for this great plugin.
The two bugs above are caused by a label tag wrapping the input field. They have been flagged as invalid, but as I must disagree, as it is valid and semantic html.
=> Fix for fields wrapped in a label

lib/picker.date.js, lib/picker.js, lib/picker.time.js
Added a new setting called `updateInput` that, when false, disables updating the input element's value. Defaults to normal bahaviour (`true`). This allows the user to respond to onSet events and set the input value themselves.
=> Added 'updateInput' setting, which can disable updating the input value

lib/picker.js
When the `editable` option is set to true, the picker will not open when clicked. When the picker is editable, keyboard events are not bound to the input element. It looks like binding for click and focus events were moved inside the conditional and are only put in place when the picker is not editable.
=> bind click and focus events when editable

lib/picker.js
fixes #1074 for activeElement is breaking $.contains() method for lower version of jQuery 1.7 but it works well with jQuery 2.1.3.
[https://codepen.io/amitesh/pen/PRLwvQ](Sample code on CodePen)
=> fixes #1074 activeElement is breaking $.contains() method

lib/translations/nl_NL.js
the short version of the dutch version of March is incorrect, it has been fixed in this pull request
=> translation of short month

lib/picker.js
In my case (and others have had trouble with this), setting `html`'s `overflow: hidden` causes the page to scroll to the top. I'm using a custom container for the picker (a child of the `body` tag).
Setting `overflow: hidden` on the body tag instead prevents the scrolling.
Closes #769
Once this is merged, would we be able to get another version release? :)
=> Use body instead of html to block overflow

lib/picker.js, tests/units/base.js
Chrome 73 changes the behaviour of click events when the mousedown is on one element
and the mouseup is on another. The previous behaviour was to not emit any click event
at all. The new behaviour is to emit a click event with the target being the
common ancestor of the elements involved.
In the case of pickadate the calendar is popped up over the input element
meaning that the mousedown event targest the input but the mouseup targest
the calendar itself. This results in the click event targetting the common
ancestor which is not particularly useful.
The workaround here is to track the mousedown and mouseup events during
calendar opening and ignore any click events generated during this.
See https://bugs.chromium.org/p/chromium/issues/detail?id=946459&can=2&q=click
for additional details. …
=> Add mousedown/up tracking to allow for change in behaviour in Chrome 73

lib/picker.js
Fixes scenarios where the library is called with undefined `this`, yet there is a browser global window object.
=> Sometimes there is no this, only window.

lib/apis/dom/index.css
Currently in Chrome on Windows we can see the default background color of the buttons.
This PR fixes this by resetting the `background` and `appearance`.
before
after
=> Reset the styles of the user agent stylesheet for buttons

lib/picker.date.js
=> Fixes the handling of unicode special characters causing errors in i18n
